// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Run after `prisma migrate reset`; also invoked directly by `npm run db:seed`.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations and introspection need a *direct* (non-transaction-pooled)
    // connection: DDL and the migration advisory lock require a real session.
    // The app runtime uses the pooled DATABASE_URL via the adapter in
    // lib/prisma.ts. Prisma 7's config has no `directUrl` key — the split is
    // made by choosing which variable is read here. Falls back to DATABASE_URL
    // for local development, where both are the same database.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
